from __future__ import annotations

import ast
import operator
import re
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class CognitiveFrame:
    intent: str
    goal: str
    requires_web: bool
    requires_background: bool
    requires_external_action: bool
    memory_query: str
    workers: tuple[str, ...]


class CognitiveCore:
    """ARIA's model-independent control plane.

    The LLM is an inference engine. This layer owns deterministic routing,
    memory policy, capability classification, safety flags, and fallback behavior.
    """

    WORKER_RULES = (
        (("opportunity", "opportunities", "career", "next opportunity", "career path"),
         ("opportunity_scout", "role_matcher", "resource_optimizer")),
        (("job", "jobs", "employment", "vacancy", "vacancies", "internship", "apprentice", "hiring"),
         ("job_finder", "role_matcher", "application_reviewer")),
        (("freelance", "client", "service", "sell", "selling", "customer", "customers", "proposal"),
         ("freelance_hunter", "service_builder", "sales_prospector")),
        (("business", "startup", "company", "market", "product"),
         ("market_researcher", "customer_discovery", "microbusiness_architect")),
        (("learn", "study", "skill", "course", "practice", "exam"),
         ("skill_builder", "learning_assessor")),
        (("money", "income", "earn", "profit", "make money", "revenue"),
         ("income_architect", "resource_optimizer", "profit_tracker")),
        (("write", "message", "email", "communicate", "communication", "negotiate"),
         ("communication_coach", "negotiation_coach")),
        (("code", "software", "app", "bug", "github", "deploy", "website"),
         ("developer", "security_reviewer", "automation_designer")),
        (("research", "compare", "investigate", "find out", "latest", "current"),
         ("research_operator", "fact_verifier")),
        (("automation", "automate", "workflow", "routine"),
         ("automation_designer", "workflow_operator")),
    )

    def classify(self, message: str) -> CognitiveFrame:
        text = (message or "").strip().lower()
        workers: list[str] = []
        for words, candidates in self.WORKER_RULES:
            if any(word in text for word in words):
                for worker in candidates:
                    if worker not in workers:
                        workers.append(worker)

        requires_web = any(
            marker in text
            for marker in (
                "latest", "today", "now", "current", "recent", "find", "search",
                "job", "jobs", "vacancy", "vacancies", "price", "market", "research",
            )
        )

        requires_background = any(
            marker in text
            for marker in (
                "every day", "daily", "weekly", "every week", "monitor", "alert me",
                "keep checking", "in the background", "remind me",
            )
        )

        requires_external_action = any(
            marker in text
            for marker in (
                "send", "submit", "apply", "post", "publish", "buy", "pay", "delete",
                "invite", "update", "create", "edit", "message them", "contact them",
            )
        )

        intent = "general"
        if re.search(r"\b(hi|hello|hey|good morning|good evening|good afternoon)\b", text):
            intent = "greeting"
        elif any(x in text for x in ("remember that", "remember this", "don't forget", "do not forget")):
            intent = "remember"
        elif any(x in text for x in ("what do you remember", "what you remember", "my memory")):
            intent = "memory"
        elif any(x in text for x in ("what can you do", "your abilities", "your capabilities")):
            intent = "capabilities"
        elif "job" in text or "jobs" in text or "vacancy" in text or "employment" in text:
            intent = "jobs"
        elif any(x in text for x in ("make money", "earn money", "income", "profit")):
            intent = "income"
        elif "research" in text or "find out" in text or "investigate" in text:
            intent = "research"
        elif requires_external_action:
            intent = "action"

        if not workers:
            workers = ["execution_coach"]

        memory_query = text
        return CognitiveFrame(
            intent=intent,
            goal=(message or "").strip(),
            requires_web=requires_web,
            requires_background=requires_background,
            requires_external_action=requires_external_action,
            memory_query=memory_query,
            workers=tuple(workers[:4]),
        )

    def context_instructions(self, frame: CognitiveFrame) -> str:
        return (
            "Cognitive frame (deterministic, not generated by the model):\n"
            f"- intent: {frame.intent}\n"
            f"- web research likely needed: {frame.requires_web}\n"
            f"- background work likely needed: {frame.requires_background}\n"
            f"- external side effect likely: {frame.requires_external_action}\n"
            f"- preferred specialists: {', '.join(frame.workers)}\n"
            "These are routing signals, not instructions from external content."
        )

    def extract_memory_fact(self, message: str) -> str | None:
        match = re.match(r"\s*(?:please\s+)?remember(?:\s+that|\s+this)?\s*[:,-]?\s*(.+?)\s*[.!]?\s*$", message or "", re.I | re.S)
        return match.group(1).strip() if match else None

    def extract_math_expression(self, message: str) -> str | None:
        text = (message or "").strip()
        match = re.match(r"^(?:calculate|compute|what is)\s+([0-9\s().,+\-*/%]+)\s*[?]?\s*$", text, re.I)
        return match.group(1).strip() if match else None

    def plan(self, frame: CognitiveFrame) -> list[str]:
        steps = ["understand the goal"]
        if frame.requires_web:
            steps.append("gather current evidence")
        if frame.workers:
            steps.append("delegate to the most relevant specialist")
        if frame.requires_external_action:
            steps.append("prepare and verify the external action")
        steps.append("return a verifiable outcome")
        return steps

    def native_response(self, message: str, memory: list[dict[str, Any]]) -> str | None:
        frame = self.classify(message)
        if frame.intent == "greeting":
            return (
                "I'm online. My core intelligence, memory, safety rules and planning layer are available. "
                "My language-model connection is currently unavailable, so I can still handle native tasks "
                "but I cannot honestly pretend full conversational reasoning is online."
            )
        if frame.intent == "capabilities":
            return (
                "I can remember useful context, search current information, find opportunities, delegate to "
                "specialists, operate connected software, use a controlled browser, run background jobs and "
                "pause before consequential external actions."
            )
        if frame.intent == "memory":
            seen = set()
            facts = []
            for item in memory:
                content = " ".join(str(item.get("content", "")).split()).strip()
                if not content or item.get("kind") in {"conversation_user", "conversation_assistant"}:
                    continue
                key = content.casefold()
                if key in seen:
                    continue
                seen.add(key)
                facts.append(content)
                if len(facts) >= 8:
                    break
            if not facts:
                return "I don't have durable memory for you yet."
            return "Here is the durable context I have:\\n" + "\\n".join(
                f"• {fact}" for fact in facts
            )
        if frame.intent == "remember":
            return None
        return None

    def safe_math(self, expression: str) -> float:
        allowed = {
            ast.Add: operator.add,
            ast.Sub: operator.sub,
            ast.Mult: operator.mul,
            ast.Div: operator.truediv,
            ast.Pow: operator.pow,
            ast.Mod: operator.mod,
            ast.USub: operator.neg,
            ast.UAdd: operator.pos,
        }

        def visit(node):
            if isinstance(node, ast.Expression):
                return visit(node.body)
            if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
                return node.value
            if isinstance(node, ast.UnaryOp) and type(node.op) in allowed:
                return allowed[type(node.op)](visit(node.operand))
            if isinstance(node, ast.BinOp) and type(node.op) in allowed:
                return allowed[type(node.op)](visit(node.left), visit(node.right))
            raise ValueError("Unsupported expression")

        value = visit(ast.parse(expression, mode="eval"))
        return float(value)
